---
title: "Group 23 Cumulative Return Plot"
date: "9/11/2022"
output: html_document
---

```{r}
library(dplyr)
library(glmnet)
library(lubridate)
library(ggplot2)
```

```{r}
data <- read.csv('NEW_48_Industry_Portfolios_Daily.csv', skip = 9, na.strings = "-99.99")

colnames(data)[1] <- 'Dates' #rename dates column

data <- data[which(data$Dates == '19880412'):which(data$Dates == '20220630'),] # 20160104 till date
```


```{r}
#Cummulative Return Code

N_industry <- c(2:49)
columns <- colnames(data)[c(1, N_industry)]

w_ew <- matrix(1/length(N_industry), nrow = length(N_industry), ncol = 1) # Get the equally weighted matrix

# N identity matrix as identified in the mathematical equation
N <- rbind(diag(length(N_industry) - 1), matrix(-1, ncol = length(N_industry) - 1)) 

# To get the starting data to collect for the 63 observations
start_row <- 1
end_row <- start_row + 63 - 1 

#slice data to obtain 48 industries with respective 63 daily returns
data1 <- data[columns][start_row:end_row,]

# convert dates column
data1 <- data1 %>% mutate(Dates = ymd(Dates))

# Scale the data such that the data is demean where the sample mean of each asset return is 0
# by specifying center=T and scale=F, we aim to subtract the mean from each individual return but NOT dividing by the standard deviation.
demean <- scale(data1[, c(2:length(columns))], center=T, scale = F) 

y <- demean %*% w_ew # Matrix multiplication of RWew
x <- demean %*% N # Matrix multiplication of RN
lasso <- cv.glmnet(x, y, alpha = 1, standardise = F, intercept = F) 
ridge <- cv.glmnet(x, y, alpha = 0, standardise = F, intercept = F) 
minvar <- lm(y ~ x)
minvar <- glmnet(x, y, lambda = 0)
```

```{r}
#applying weights of coefficients.
lasso_beta <- t(matrix(coef(lasso, s = "lambda.min")))[-1] #or should we use lambda.1se?
ridge_beta <- t(matrix(coef(ridge, s = "lambda.min")))[-1]
minvar_beta <- t(matrix(coef(minvar)))[-1]

lasso_weights <- w_ew - N %*% lasso_beta
ridge_weights <- w_ew - N %*% ridge_beta
minvar_weights <- w_ew - N %*% minvar_beta

```


```{r}
daily_returns <- function(weights, df){
  # weights = lasso_weights
  # df = data1
  #function to return vector of daily returns
  #initialise vector of returns
  returns <- c()
  #for loop to generate returns from lasso regularised model
  for (i in 1:nrow(df)){
    #sumproduct weights and individual returns
    day_return <- crossprod(as.vector(weights), as.numeric(as.vector(df[i, 2:ncol(df)])))
    #append weighted return
    returns <- append(returns, day_return)
  }
  return (returns)
}
```


```{r}
lasso_daily_returns <- daily_returns(lasso_weights, data)
ridge_daily_returns <- daily_returns(ridge_weights, data)
ew_daily_returns <- daily_returns(w_ew, data)
minvar_daily_returns <- daily_returns(minvar_weights, data)

#initialise vector of cumulative returns with initial investment of $1 for both ridge and lasso
cum_lasso_returns_vector <- c(1* (1 + lasso_daily_returns[1] / 100))
cum_ridge_returns_vector <- c(1 * (1 + ridge_daily_returns[1] / 100))
cum_ew_returns_vector <- c(1 * (1 + ew_daily_returns[1] / 100))
cum_minvar_returns_vector <- c(1 * (1 + minvar_daily_returns[1] / 100))
```


```{r}
cum_return <- function(df, return_vector, cum_return_vector){
  #function returns cum return for initial investment of $1000 
  #inputs 'return vector' is the vector of daily returns
  # df = data1
  # return_vector = lasso_daily_returns
  # cum_return_vector = cum_lasso_returns_vector
  for (i in 2:nrow(df)){
    #i = 1
    # return of that day
    return <- 1 + return_vector[i] / 100
    # new cum return based on previous day daily return
    new_cum_r <- cum_return_vector[i - 1] * return
    # append new cum return
    cum_return_vector <- append(cum_return_vector, new_cum_r)
  }
  return (cum_return_vector)
}
```


```{r}
lasso_cum_return <- cum_return(data, lasso_daily_returns, cum_lasso_returns_vector) #lasso regularised cum return
ridge_cum_return <- cum_return(data, ridge_daily_returns, cum_ridge_returns_vector) #ridge regularised cum return
ew_cum_return <- cum_return(data, ew_daily_returns, cum_ew_returns_vector) #equally weighted cum return
minvar_cum_return <- cum_return(data, minvar_daily_returns, cum_minvar_returns_vector) #equally weighted cum return

#create returns dataframe
returns_df <- data %>% 
  select(Dates) %>%
  mutate(Dates = ymd(Dates),
         Ridge_Cum_Return = ridge_cum_return,
         Lasso_Cum_Return = lasso_cum_return,
         EW_Cum_Return = ew_cum_return,
         MinVar_Cum_Return = minvar_cum_return)
```

##plotting graph
```{r}
ggplot(returns_df, aes(x = Dates)) +
  geom_line(aes(y = Ridge_Cum_Return, color = "Ridge")) +
  geom_line(aes(y = Lasso_Cum_Return, color = "LASSO")) +
  geom_line(aes(y = EW_Cum_Return, color = "Equally-Weighted")) +
  geom_line(aes(y = MinVar_Cum_Return, color = "MinVar")) +
  scale_color_manual(name = "Legend", 
                     values = c(
                       "Ridge" = "blue", 
                       "LASSO" = "red", 
                       "Equally-Weighted" = "black",
                       "MinVar" = "darkred"
                       )
                     ) +
  labs(title = "Cumulative Return", subtitle = "based on $1 initial investment", y = '', x = "Dates") +
  theme(plot.title = element_text(face="bold"),
        plot.subtitle = element_text(face = "italic"))
```

```{r}
df <- read.csv('NEW_48_Industry_Portfolios_Daily.csv', skip = 9, na.strings = "-99.99")

colnames(df)[1] <- 'Dates' #rename dates column
df$Dates <- as.character(df$Dates)
n_ind = ncol(df)
train_end_idx = which(df$Dates == "20220103") 
n_train = 63
train_idx = (train_end_idx - n_train + 1):train_end_idx 
df_train = df[train_idx, ]
n_ind_selected = 6
w_EW = rep(1/n_ind_selected, n_ind_selected)
N = rbind(diag(n_ind_selected - 1), -1)
# ind_idx = sample(1:n_ind, n_ind_selected)
ind_idx = 2:(n_ind_selected+1)
df_selected = df_train[,ind_idx]
df_demean = scale(df_selected, center = TRUE, scale = FALSE)
y = df_demean %*% w_EW 
X = df_demean %*% N
minvar = lm(y ~ X)

minvar_beta <- t(matrix(coef(minvar)))[-1]
minvar_weights <- w_EW - N %*% minvar_beta

weights_str <- 
  paste(
  "MinVar Weights: ",
  paste0("Agric: ", minvar_weights[1]),
  paste0("Food: ", minvar_weights[2]),
  paste0("Soda: ", minvar_weights[3]),
  paste0("Beer: ", minvar_weights[4]),
  paste0("Smoke: ", minvar_weights[5]),
  paste0("Toys: ", minvar_weights[6]),
  sep = "\n")

cat(weights_str)
```

